### ISSUE TITLE
Importing Adobe Commerce Event Collector in React

### ISSUE THREAD

**Issue by srijansahaa** [AdobeDocs/commerce-services#36]
How do we Import Adobe Commerce Event Collector in React JS?  As mentioned in the guide, After loading the collector script, or importing the package as shown below, there is nothing else that needs to be done.
`import "@adobe/magento-storefront-event-collector";`
So is it enough to import this in the root file or do we have to do any other configuration as well?

**Comment by keharper** [comment]
@erikmarr Is this something you can answer?

**Comment by erikmarr** [comment]
Hi @srijansahaa thanks for reaching out. I believe this is all you have to do, but I'm checking with our development team for confirmation.

**Comment by erikmarr** [comment]
Hi @srijansahaa I've confirmed that is all you need to do. Please open a separate ticket if there is a specific issue you are encountering. Thank you.
